version: '3.3'
services:
  integrationsites:
    image: sc-registry.fredhutch.org/integrationsites:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.integrationsites.rule=Host(`integrationsites.fredhutch.org`)"
        - "traefik.http.routers.integrationsites-secured.rule=Host(`integrationsites.fredhutch.org`)"
        - "traefik.http.routers.integrationsites.entrypoints=web,web-secured"
        - "traefik.http.services.integrationsites.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.integrationsites.tls=true"

networks:
  sc-swarm-net:
    external: true